modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
logoFile="info.png"
description='''
Adds synchronized, linkable speakers for Etched. Connect multiple speakers to vanilla Jukeboxes playing Etched records or to Etched Album Jukeboxes, with individual volume and range controls.
'''

[[mixins]]
config="etchedspeakers.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="etched"
type="required"
versionRange="[${etched_version}]"
ordering="AFTER"
side="BOTH"
